# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Release & Publish to bazel_registry

# This workflow handles tagging, GitHub release creation, and publishing to bazel_registry.
# While technically separate topics, they are meant to be absolutely in sync, so they are handled via this single workflow.

# Use Cases:
# 1) Manual release with new tag: Create tag, release, and publish from specified ref (branch/commit/tag)
# 2) Automatic release from tag push: Triggered when a v* tag is pushed, release and publish to bazel_registry
# 3) Automatic release from GitHub release: Triggered when a release is created on GitHub, publish to bazel_registry
# 4) Recovery - existing tag: Re-run with pre-existing tag to release and publish to bazel_registry
# 5) Recovery - existing release: Re-run with pre-existing GitHub release to publish to bazel_registry

on:
  workflow_call:
    inputs:
      version:
        description: "New Version (SemVer & PEP 440 compatible)"
        required: true
        type: string
      ref:
        description: "Git ref to release (branch, tag, or commit hash). Required if tag does not exist yet."
        required: false
        default: "main"
        type: string

permissions:
  contents: read

jobs:
  verify-tag:
    name: Verify Naming Convention of Tag and Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Determine tag
        id: tag
        run: |
          # Determine the tag name based on event type
          # (tag push, release or workflow_dispatch)
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "::debug:: Event is a tag push"
            if [[ "${GITHUB_REF_TYPE}" != "tag" ]]; then
              echo "::error:: Expected a tag ref, but got '${GITHUB_REF_TYPE}'"
              exit 1
            fi
            # drop prefix "refs/tags/"
            TAG="${GITHUB_REF_NAME#refs/tags/}"
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "::debug:: Event is a release"
            TAG="${{ github.event.release.tag_name }}"
          else
            echo "::debug:: Event is a workflow_dispatch"
            TAG="v${{ github.event.inputs.version }}"
          fi
          echo "Tag: $TAG" >> "$GITHUB_STEP_SUMMARY"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Validate tag matches PEP 440
        run: |
          set -euo pipefail
          TAG="${{ steps.tag.outputs.tag }}"
          VERSION="${TAG#v}"
          python -c "from packaging.version import Version; Version('$VERSION')"

      - name: Validate release name matches git tag
        if: github.event_name == 'release'
        run: |
          # The release name and tag must match,
          # e.g. Tag: "v1.2.3", Release Name: "v1.2.3 - Some description"
          set -euo pipefail
          TAG="${{ steps.tag.outputs.tag }}"
          RELEASE_NAME="${{ github.event.release.name }}"
          echo "Release Name: $RELEASE_NAME" >> "$GITHUB_STEP_SUMMARY"
          if [[ "$RELEASE_NAME" != "$TAG"* ]]; then
            echo "::error:: Release name '$RELEASE_NAME' does not start with tag '$TAG'"
            exit 1
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: verify-tag
    concurrency:
      group: dash-license-scan-${{ needs.verify-tag.outputs.tag }}-build
      cancel-in-progress: true
    outputs:
      requires_tag_push: ${{ steps.create_tag.outputs.requires_tag_push }}
    steps:
      - name: Determine ref to checkout
        id: ref
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            REF="${{ github.event.inputs.ref }}"
          else
            REF="${{ github.ref }}"
          fi
          echo "ref=$REF" >> "$GITHUB_OUTPUT"
          echo "Building from: $REF" >> "$GITHUB_STEP_SUMMARY"


      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install build tools
        run: pip install hatch packaging twine

      - name: Create tag (local only; if needed)
        id: create_tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          set -euo pipefail
          TAG="${{ needs.verify-tag.outputs.tag }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
            echo "requires_tag_push=false" >> "$GITHUB_OUTPUT"
          else
            git tag "$TAG"
            echo "requires_tag_push=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Build
        run: hatch build

      - name: Validate with twine
        run: twine check dist/*

      - name: Smoke test wheel (uvx)
        run: |
          WHEEL=$(ls dist/*.whl | head -n1)
          uvx --from "$WHEEL" dash-license-scan --version

      - name: Smoke test wheel (pip)
        run: |
          python -m venv wheel-test-env
          . wheel-test-env/bin/activate
          pip install dist/*.whl
          dash-license-scan --version
          deactivate

      - name: Smoke test sdist (uv)
        run: |
          SDIST=$(ls dist/*.tar.gz | head -n1)
          uv venv .venv-sdist
          uv pip install --python .venv-sdist "$SDIST"
          .venv-sdist/bin/dash-license-scan --version

      - name: Smoke test sdist (pip)
        run: |
          python -m venv sdist-test-env
          . sdist-test-env/bin/activate
          pip install dist/*.tar.gz
          dash-license-scan --version
          deactivate

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist/*

  publish:
    name: Publish
    needs:
      - build
      - verify-tag
    runs-on: ubuntu-latest
    concurrency:
      group: dash-license-scan-${{ needs.verify-tag.outputs.tag }}-publish
      # Do not cancel in-progress publish jobs to avoid partial publishes
      cancel-in-progress: false
    environment:
      name: pypi
      url: https://pypi.org/project/dash-license-scan/
    permissions:
      contents: write # Push tag
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist

      - uses: actions/checkout@v4
        if: needs.build.outputs.requires_tag_push == 'true'

      - name: push tag (if needed)
        if: needs.build.outputs.requires_tag_push == 'true'
        run: |
          set -euo pipefail
          TAG="${{ needs.verify-tag.outputs.tag }}"
          # As this is a separate job, we need to re-create the tag here
          git tag "$TAG"
          git push --tags

      - name: Create GitHub Release (if needed)
        if: github.event_name != 'release'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAG="${{ needs.verify-tag.outputs.tag }}"
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release $TAG already exists. Verified."
          else
            gh release create "$TAG" --title "$TAG" --generate-notes
          fi

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
